name: "Tests"

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  tests:
    name: "Tests"
    runs-on: ubuntu-20.04
    
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"
      
      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "8.1"
          tools: composer
      
      - name: "Install dependencies"
        uses: "ramsey/composer-install@v2"
        with:
          composer-options: "--ansi --no-interaction"
      
      - name: "Run tests"
        run: "composer tests"
